spring:
  application:
    name: EventHub
  profiles:
    include:
      - server
      - db
security:
  jwt:
    secret-key: CgTOA2QC9nxYspeBZBRsEIoDmpBbGTjfDCE6WfnOHHrA7rgHafqC5u1m6GL22pNY
    expiration: 300000
